# Generated by Django 4.2.4 on 2024-12-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=50)),
                ('contraseña_original', models.CharField(blank=True, max_length=128, null=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=15)),
                ('f_nac', models.DateField(null=True)),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('grupos', models.ManyToManyField(blank=True, to='auth.group')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('permisos', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
        ),
    ]
