# Generated by Django 4.2.4 on 2024-12-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosInactivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=50)),
                ('contraseña_original', models.CharField(blank=True, max_length=128, null=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=15)),
                ('f_nac', models.DateField(null=True)),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('fecha_inactivacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios_inactivos',
            },
        ),
    ]
