# Generated by Django 4.2.4 on 2024-12-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_usuarios_nivel_triaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nivel_triaje',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='sintomas',
        ),
        migrations.RemoveField(
            model_name='usuariosinactivos',
            name='sintomas',
        ),
    ]
