# Generated by Django 4.2.4 on 2024-12-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_remove_usuarios_nivel_triaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('En espera', 'En espera'), ('En triaje', 'En triaje'), ('En consulta', 'En consulta'), ('Atendido', 'Atendido')], default='En espera', max_length=20)),
                ('tiempo_ingreso', models.DateTimeField(auto_now_add=True)),
                ('tiempo_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
